### ISSUE TITLE
it's overlapping the Atom hints thing.

### ISSUE THREAD

**Issue by rokyed** [RodrigoEspinosa/atom-hacker-news-background-titles#1]
it's overlapping the Atom hints thing. It's a visual bug , but makes titles unreadable.

**Comment by RodrigoEspinosa** [comment]
@rokyed you should use one or the other, just like `autocomplete-plus` that replaced the old `autocomplete`.

I should mention that on the README.

Thank you for mentioning this :fireworks:

**Comment by rokyed** [comment]
oh sorry i did not knew that i did it later and yes is good , but on my
opinion , it would be great to have them both n__n , i suppose you could
put an option button for that.
Besides that , it is awesome , i really like it. Keep up with the good work
n__n!!
